### PR TITLE
fixed option Ignore hidden layers

### PR DESCRIPTION
**Pull request by andeon**
Tested on Linux and WIndows on Inkscape 0.91.

### CODE REVIEW

**Comment by jleclanche** [comment]
That doesn't sound right, `display:none` is not the default style. If a layer doesn't have a style, it's shown.

**Comment by andeon** [comment]
I not sure about. but before fix I have an error message:

``` pytb
Traceback (most recent call last):
  File "spine_exporter.py", line 279, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "spine_exporter.py", line 242, in effect
    style = parse_css_style(layer.attrib.get("style", ""))
  File "spine_exporter.py", line 26, in parse_css_style
    k, v = directive.split(":")
ValueError: need more than 1 value to unpack
```

**Comment by jleclanche** [comment]
I see. I'll fix it.

**Comment by andeon** [comment]
Thanks :)

**Pull request closed without merging**
